drop table PROJECT CASCADE CONSTRAINTS;

CREATE TABLE PROJECT(
	PNO INT, 
	PNAME VARCHAR2(30), 
	BUDGET NUMBER, 
	LOCATION VARCHAR2(20),
    PRIMARY KEY(PNO)
	); 
	
--INSERT INTO PROJECT
--VALUES(1,'',,'');

INSERT INTO PROJECT
VALUES(1,'Instrumental',150000,'Montreal');

INSERT INTO PROJECT
VALUES(2,'Database Dev',135000,'New York');
INSERT INTO PROJECT
VALUES(3,'CAM/CAD',250000,'New York');
INSERT INTO PROJECT
VALUES(4,'Maintenance',310000,'Orlando');

COMMIT;