SET SERVEROUTPUT ON;
SET VERIFY OFF;


CREATE OR REPLACE FUNCTION BOND(x IN AAM.COLNAME%TYPE, y IN AAM.COLNAME%TYPE)
RETURN NUMBER
IS
VALX NUMBER:=0;
VALY NUMBER:=0;
PLSQL1 VARCHAR(500);
PLSQL2 VARCHAR(500);
TERM NUMBER:=0;
TOTAL NUMBER:=0;
BEGIN
	TERM :=0;
	TOTAL :=0;
	IF (X = '0' OR Y='0') THEN
		RETURN 0;
	END IF;
	FOR R IN (SELECT * FROM AAM) LOOP
		PLSQL1 := 'SELECT  AAM.'|| X ||' '||'FROM AAM WHERE AAM.COLNAME = '||''''||R.COLNAME ||'''';
		PLSQL2 := 'SELECT  AAM.'|| Y ||' '||'FROM AAM WHERE AAM.COLNAME = '||''''||R.COLNAME ||'''';
		EXECUTE IMMEDIATE PLSQL1 INTO VALX;
		EXECUTE IMMEDIATE PLSQL2 INTO VALY;
		TERM := VALX*VALY;
		TOTAL := TOTAL+TERM;
		
	END LOOP;
	
	RETURN TOTAL;
END BOND;
/