SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE FUNCTION INSERTING_TEMPCAM2
RETURN NUMBER
IS
PRAGMA AUTONOMOUS_TRANSACTION;
plsql_block VARCHAR2(500) :='COMMIT';
BEGIN	
	FOR R IN(SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TEMPCAM2' AND NOT COLUMN_NAME='COLNAME') LOOP
		INSERT INTO TEMPCAM2 VALUES(R.COLUMN_NAME,0,0,0,0);
	END LOOP;
	EXECUTE IMMEDIATE plsql_block;
	RETURN 1;
END INSERTING_TEMPCAM2;
/

SELECT INSERTING_TEMPCAM2 FROM DUAL;
COMMIT;
