SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE FUNCTION INSERTING_TEMPCAM1
RETURN NUMBER
IS
PRAGMA AUTONOMOUS_TRANSACTION;
plsql_block VARCHAR2(500) :='COMMIT';
BEGIN	
	INSERT INTO TEMPCAM1 VALUES('A1',0,0,0);
	INSERT INTO TEMPCAM1 VALUES('A2',0,0,0);
	INSERT INTO TEMPCAM1 VALUES('A3',0,0,0);
	INSERT INTO TEMPCAM1 VALUES('A4',0,0,0);
	EXECUTE IMMEDIATE plsql_block;
	RETURN 1;
END INSERTING_TEMPCAM1;
/

SELECT INSERTING_TEMPCAM1 FROM DUAL;
-- SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TEMPCAM1';