SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE FUNCTION UPDATE_TEMPCAM1
RETURN NUMBER
IS
PRAGMA AUTONOMOUS_TRANSACTION;
plsql_block VARCHAR2(500) :='COMMIT';
BEGIN	
UPDATE TEMPCAM1 SET TEMPCAM1.A1= (SELECT AAM.A1 FROM AAM WHERE COLNAME = 'A1' ) WHERE COLNAME = 'A1';
UPDATE TEMPCAM1 SET TEMPCAM1.A1= (SELECT AAM.A1 FROM AAM WHERE COLNAME = 'A2' ) WHERE COLNAME = 'A2';
UPDATE TEMPCAM1 SET TEMPCAM1.A1= (SELECT AAM.A1 FROM AAM WHERE COLNAME = 'A3' ) WHERE COLNAME = 'A3';
UPDATE TEMPCAM1 SET TEMPCAM1.A1= (SELECT AAM.A1 FROM AAM WHERE COLNAME = 'A4' ) WHERE COLNAME = 'A4';

UPDATE TEMPCAM1 SET TEMPCAM1.A2= (SELECT AAM.A2 FROM AAM WHERE COLNAME = 'A1' ) WHERE COLNAME = 'A1';
UPDATE TEMPCAM1 SET TEMPCAM1.A2= (SELECT AAM.A2 FROM AAM WHERE COLNAME = 'A2' ) WHERE COLNAME = 'A2';
UPDATE TEMPCAM1 SET TEMPCAM1.A2= (SELECT AAM.A2 FROM AAM WHERE COLNAME = 'A3' ) WHERE COLNAME = 'A3';
UPDATE TEMPCAM1 SET TEMPCAM1.A2= (SELECT AAM.A2 FROM AAM WHERE COLNAME = 'A4' ) WHERE COLNAME = 'A4';

UPDATE TEMPCAM1 SET TEMPCAM1.A3= (SELECT AAM.A3 FROM AAM WHERE COLNAME = 'A1' ) WHERE COLNAME = 'A1';
UPDATE TEMPCAM1 SET TEMPCAM1.A3= (SELECT AAM.A3 FROM AAM WHERE COLNAME = 'A2' ) WHERE COLNAME = 'A2';
UPDATE TEMPCAM1 SET TEMPCAM1.A3= (SELECT AAM.A3 FROM AAM WHERE COLNAME = 'A3' ) WHERE COLNAME = 'A3';
UPDATE TEMPCAM1 SET TEMPCAM1.A3= (SELECT AAM.A3 FROM AAM WHERE COLNAME = 'A4' ) WHERE COLNAME = 'A4';
	
	
EXECUTE IMMEDIATE plsql_block;
RETURN 1;
END UPDATE_TEMPCAM1;
/

SELECT UPDATE_TEMPCAM1 FROM DUAL;