SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE FUNCTION CAM_INITIALIZE
RETURN NUMBER
IS
plsql_block1 VARCHAR2(500) :='COMMIT';
BEGIN	
	UPDATE CAM SET CAM.A1= (SELECT AAM.A1 FROM AAM WHERE COLNAME = 'A1' ) WHERE COL = 'A1';
	UPDATE CAM SET CAM.A1= (SELECT AAM.A1 FROM AAM WHERE COLNAME = 'A2' ) WHERE COL = 'A2';
	UPDATE CAM SET CAM.A1= (SELECT AAM.A1 FROM AAM WHERE COLNAME = 'A3' ) WHERE COL = 'A3';
	UPDATE CAM SET CAM.A1= (SELECT AAM.A1 FROM AAM WHERE COLNAME = 'A4' ) WHERE COL = 'A4';
	
	UPDATE CAM SET CAM.A2= (SELECT AAM.A2 FROM AAM WHERE COLNAME = 'A1' ) WHERE COL = 'A1';
	UPDATE CAM SET CAM.A2= (SELECT AAM.A2 FROM AAM WHERE COLNAME = 'A2' ) WHERE COL = 'A2';
	UPDATE CAM SET CAM.A2= (SELECT AAM.A2 FROM AAM WHERE COLNAME = 'A3' ) WHERE COL = 'A3';
	UPDATE CAM SET CAM.A2= (SELECT AAM.A2 FROM AAM WHERE COLNAME = 'A4' ) WHERE COL = 'A4';
	EXECUTE IMMEDIATE plsql_block1;
	RETURN 1;
END CAM_INITIALIZE;
/