---For Creating AAM
SELECT * FROM FM A NATURAL JOIN FM@SITE1 B ;
CREATE OR REPLACE PROCEDURE CREATEAAM
IS
C number :=0;
TOTAL NUMBER :=0;
COLNO NUMBER :=1;
COLNAME VARCHAR2(5);
plsql_block VARCHAR2(500);
plsql_block1 VARCHAR2(500) :='COMMIT';
VAL NUMBER :=0;
BEGIN
	---------MAKING SUMOFFM TABLE-----------
	select count(COLUMN_NAME) into C from ALL_TAB_COLUMNS where TABLE_NAME='FM';
	FOR R IN (SELECT * FROM FM) LOOP
	
			WHILE (COLNO<C) LOOP
			COLNAME := CONCAT('S',TO_CHAR(COLNO));
			plsql_block := 'SELECT ' || COLNAME  ||'  '|| ' FROM FM WHERE FM.QNO = '||R.QNO;
			EXECUTE IMMEDIATE plsql_block INTO VAL;
			TOTAL := TOTAL+VAL;
			COLNO := COLNO+1;
			END LOOP;
		--DBMS_OUTPUT.PUT_LINE(TOTAL);
		INSERT INTO SUMOFFM values(R.QNO,TOTAL);
		EXECUTE IMMEDIATE plsql_block1;
		TOTAL:=0;
		COLNO :=1;
	END LOOP;
	----------------------------------------
	
	
	-----UPDATING AAM VALUES
	
	---DIAGONAL VALUES
	UPDATE AAM SET AAM.A1 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A1=1)) WHERE AAM.COLNAME = 'A1';
	UPDATE AAM SET AAM.A2 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A2=1)) WHERE AAM.COLNAME = 'A2';
	UPDATE AAM SET AAM.A3 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A3=1)) WHERE AAM.COLNAME = 'A3';
	UPDATE AAM SET AAM.A4 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A4=1)) WHERE AAM.COLNAME = 'A4';
	
	EXECUTE IMMEDIATE plsql_block1;
	
	UPDATE AAM SET AAM.A2 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A1=1 AND AUM.A2=1)) WHERE AAM.COLNAME = 'A1';
	UPDATE AAM SET AAM.A1 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A1=1 AND AUM.A2=1)) WHERE AAM.COLNAME = 'A2';
	
	UPDATE AAM SET AAM.A3 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A1=1 AND AUM.A3=1)) WHERE AAM.COLNAME = 'A1';
	UPDATE AAM SET AAM.A1 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A1=1 AND AUM.A3=1)) WHERE AAM.COLNAME = 'A3';
	
	UPDATE AAM SET AAM.A1 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A1=1 AND AUM.A4=1)) WHERE AAM.COLNAME = 'A4';
	UPDATE AAM SET AAM.A4 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A1=1 AND AUM.A4=1)) WHERE AAM.COLNAME = 'A1';
	
	UPDATE AAM SET AAM.A2 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A3=1 AND AUM.A2=1)) WHERE AAM.COLNAME = 'A3';
	UPDATE AAM SET AAM.A3 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A3=1 AND AUM.A2=1)) WHERE AAM.COLNAME = 'A2';
	
	UPDATE AAM SET AAM.A2 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A4=1 AND AUM.A2=1)) WHERE AAM.COLNAME = 'A4';
	UPDATE AAM SET AAM.A4 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A4=1 AND AUM.A2=1)) WHERE AAM.COLNAME = 'A2';
	
	UPDATE AAM SET AAM.A3 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A3=1 AND AUM.A4=1)) WHERE AAM.COLNAME = 'A4';
	UPDATE AAM SET AAM.A4 = (SELECT NVL(SUM(SUMOFSITES),0) FROM SUMOFFM WHERE SUMOFFM.QNO IN (SELECT AUM.QNO FROM AUM WHERE AUM.A3=1 AND AUM.A4=1)) WHERE AAM.COLNAME = 'A3';
	EXECUTE IMMEDIATE plsql_block1;

END CREATEAAM;
/