---For Creating TEMPCAM1

CREATE OR REPLACE PROCEDURE CREATE_TEMPCAM1
IS
F1 NUMBER;
F2 NUMBER;
F3 NUMBER;
ALTR VARCHAR2(500);
COMM VARCHAR2(10):='COMMIT';
BEGIN
	
	F1 := CONT('0','A3','A1');
	F2 := CONT ('A1','A3','A2');
	F3 := CONT ('A2','A3','0');
	DBMS_OUTPUT.PUT_LINE(F1 ||' -> '|| F2||' -> '|| F3);
	
	IF(F1>F2 AND F1>F3) THEN 
		--A3,A1,A2
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A3 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A1 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A2 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		EXECUTE IMMEDIATE COMM;
	ELSIF(F2>F3 AND F2>F1) THEN
		--A1,A3,A2
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A1 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A3 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A2 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		EXECUTE IMMEDIATE COMM;
	ELSIF(F3>F1 AND F3>F2)THEN
		--A1,A2,A3
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A1 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A2 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		ALTR := 'ALTER TABLE TEMPCAM1 ADD A3 NUMBER';
		EXECUTE IMMEDIATE ALTR;
		EXECUTE IMMEDIATE COMM;
	END IF;

END CREATE_TEMPCAM1;
/
COMMIT;