SET SERVEROUTPUT ON;
SET VERIFY OFF;

ACCEPT TNAME CHAR PROMPT 'ENTER TABLE NAME : '

DECLARE
	TABLENAME varchar2(20):= '&TNAME';
	COLNAME VARCHAR2(10);
	COLNO NUMBER := 1;
	plsql_block1 VARCHAR2(500);
	F NUMBER;
	FF NUMBER;
	INCORRECT_INPUT EXCEPTION;
BEGIN
	
	---CREATING EMPTY RECORDS IN AUM
	FOR C IN (SELECT * FROM QUERIES) LOOP
		INSERT INTO AUM VALUES(C.QNO, 0, 0, 0, 0);
	END LOOP;
	plsql_block1 := 'COMMIT';
	EXECUTE IMMEDIATE plsql_block1;
	
	--- COMPLETING AUM
	FOR R IN (select COLUMN_NAME from ALL_TAB_COLUMNS where TABLE_NAME=TABLENAME) LOOP
		
		COLNAME := R.COLUMN_NAME;
		COUNTCOL(COLNAME,COLNO);
		COLNO := COLNO +1;
		
	END LOOP;
	
	
	CREATEAAM;
	F := CAM_INITIALIZE;
	
	CREATE_TEMPCAM1;

EXCEPTION
	WHEN INCORRECT_INPUT THEN 
		DBMS_OUTPUT.PUT_LINE('PUT CORRECT TABLE NAME.');
	WHEN TOO_MANY_ROWS THEN
		DBMS_OUTPUT.PUT_LINE('Many rows detected');
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('Data not found');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('Other errors');

END;
/








